---
abstract: 'Fast random UUID generator using the Mersenne Twister algorithm'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::AllUtils: 0
  List::Util: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-UUID-MT
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Data::UUID::MT:
    file: lib/Data/UUID/MT.pm
    version: 1.001
requires:
  Config: 0
  Math::Random::MT::Auto: 0
  Scalar::Util: 1.10
  Time::HiRes: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/data-uuid-mt/issues
  homepage: https://metacpan.org/release/Data-UUID-MT
  repository: git://github.com/dagolden/data-uuid-mt.git
version: 1.001
x_contributors:
  - 'Matt Koscica <matt.koscica@gmail.com>'
