---
abstract: 'Fast random UUID generator using the Mersenne Twister algorithm'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  List::AllUtils: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.112150'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-UUID-MT
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Data::UUID::MT:
    file: lib/Data/UUID/MT.pm
    version: 0.002
requires:
  Config: 0
  Math::Random::MT::Auto: 0
  Scalar::Util: 1.10
  Time::HiRes: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-UUID-MT
  homepage: http://github.com/dagolden/data-uuid-mt
  repository: http://github.com/dagolden/data-uuid-mt
version: 0.002
